[2023-06-12T08:36:51.682+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Var_dag.dag_var manual__2023-06-12T07:58:34.657456+00:00 [queued]>
[2023-06-12T08:36:51.730+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Var_dag.dag_var manual__2023-06-12T07:58:34.657456+00:00 [queued]>
[2023-06-12T08:36:51.731+0000] {taskinstance.py:1308} INFO - Starting attempt 3 of 6
[2023-06-12T08:36:51.774+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): dag_var> on 2023-06-12 07:58:34.657456+00:00
[2023-06-12T08:36:51.782+0000] {standard_task_runner.py:57} INFO - Started process 1527 to run task
[2023-06-12T08:36:51.791+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Var_dag', 'dag_var', 'manual__2023-06-12T07:58:34.657456+00:00', '--job-id', '295', '--raw', '--subdir', 'DAGS_FOLDER/variable_dag.py', '--cfg-path', '/tmp/tmp95t8023u']
[2023-06-12T08:36:51.792+0000] {standard_task_runner.py:85} INFO - Job 295: Subtask dag_var
[2023-06-12T08:36:51.891+0000] {task_command.py:410} INFO - Running <TaskInstance: Var_dag.dag_var manual__2023-06-12T07:58:34.657456+00:00 [running]> on host 03cd9a7904e9
[2023-06-12T08:36:52.083+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Raja' AIRFLOW_CTX_DAG_ID='Var_dag' AIRFLOW_CTX_TASK_ID='dag_var' AIRFLOW_CTX_EXECUTION_DATE='2023-06-12T07:58:34.657456+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-06-12T07:58:34.657456+00:00'
[2023-06-12T08:36:52.105+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/variable_dag.py", line 7, in print_variable
    var_sample_json=Variable.get('sample_json',deserialize_json=True)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 145, in get
    obj = json.loads(var_val)
  File "/usr/local/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 34 (char 33)
[2023-06-12T08:36:52.121+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=Var_dag, task_id=dag_var, execution_date=20230612T075834, start_date=20230612T083651, end_date=20230612T083652
[2023-06-12T08:36:52.149+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 295 for task dag_var (Expecting value: line 1 column 34 (char 33); 1527)
[2023-06-12T08:36:52.200+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-12T08:36:52.253+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
