[2023-06-11T05:15:08.422+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_pythonoperator_12.first_task scheduled__2023-06-07T00:00:00+00:00 [queued]>
[2023-06-11T05:15:09.122+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_pythonoperator_12.first_task scheduled__2023-06-07T00:00:00+00:00 [queued]>
[2023-06-11T05:15:09.127+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 6
[2023-06-11T05:15:12.115+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): first_task> on 2023-06-07 00:00:00+00:00
[2023-06-11T05:15:12.308+0000] {standard_task_runner.py:57} INFO - Started process 247 to run task
[2023-06-11T05:15:12.481+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag_pythonoperator_12', 'first_task', 'scheduled__2023-06-07T00:00:00+00:00', '--job-id', '55', '--raw', '--subdir', 'DAGS_FOLDER/python_operator_dag.py', '--cfg-path', '/tmp/tmp0k25yeox']
[2023-06-11T05:15:12.503+0000] {standard_task_runner.py:85} INFO - Job 55: Subtask first_task
[2023-06-11T05:15:14.683+0000] {task_command.py:410} INFO - Running <TaskInstance: dag_pythonoperator_12.first_task scheduled__2023-06-07T00:00:00+00:00 [running]> on host 69e374580eab
[2023-06-11T05:15:16.947+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Raja' AIRFLOW_CTX_DAG_ID='dag_pythonoperator_12' AIRFLOW_CTX_TASK_ID='first_task' AIRFLOW_CTX_EXECUTION_DATE='2023-06-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-06-07T00:00:00+00:00'
[2023-06-11T05:15:17.032+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/python_operator_dag.py", line 13, in first
    first_name=ti.xcom_pull(task_ids=get_name,key='first_name')
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2441, in xcom_pull
    task_id_whens = {tid: i for i, tid in enumerate(task_ids)}
TypeError: 'function' object is not iterable
[2023-06-11T05:15:17.195+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_pythonoperator_12, task_id=first_task, execution_date=20230607T000000, start_date=20230611T051508, end_date=20230611T051517
[2023-06-11T05:15:17.531+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 55 for task first_task ('function' object is not iterable; 247)
[2023-06-11T05:15:17.707+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-11T05:15:18.249+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
