[2023-06-10T16:30:37.836+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_pythonoperator.second_task scheduled__2023-06-07T00:00:00+00:00 [queued]>
[2023-06-10T16:30:42.834+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_pythonoperator.second_task scheduled__2023-06-07T00:00:00+00:00 [queued]>
[2023-06-10T16:30:42.836+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 6
[2023-06-10T16:30:45.500+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): second_task> on 2023-06-07 00:00:00+00:00
[2023-06-10T16:30:48.005+0000] {standard_task_runner.py:57} INFO - Started process 4447 to run task
[2023-06-10T16:30:50.114+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag_pythonoperator', 'second_task', 'scheduled__2023-06-07T00:00:00+00:00', '--job-id', '1374', '--raw', '--subdir', 'DAGS_FOLDER/Pythonoperator_dag.py', '--cfg-path', '/tmp/tmpp77e2gjk']
[2023-06-10T16:30:52.291+0000] {standard_task_runner.py:85} INFO - Job 1374: Subtask second_task
[2023-06-10T16:32:41.218+0000] {task_command.py:410} INFO - Running <TaskInstance: dag_pythonoperator.second_task scheduled__2023-06-07T00:00:00+00:00 [running]> on host e326d5f70fa9
[2023-06-10T16:32:47.829+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Raja' AIRFLOW_CTX_DAG_ID='dag_pythonoperator' AIRFLOW_CTX_TASK_ID='second_task' AIRFLOW_CTX_EXECUTION_DATE='2023-06-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-06-07T00:00:00+00:00'
[2023-06-10T16:32:48.009+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/Pythonoperator_dag.py", line 16, in retur_values
    first_name=ti.xcom_pull(task_ids=get_name,key='first_name')
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2441, in xcom_pull
    task_id_whens = {tid: i for i, tid in enumerate(task_ids)}
TypeError: 'function' object is not iterable
[2023-06-10T16:32:48.309+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_pythonoperator, task_id=second_task, execution_date=20230607T000000, start_date=20230610T163039, end_date=20230610T163248
[2023-06-10T16:32:48.397+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 1374 for task second_task ('function' object is not iterable; 4447)
[2023-06-10T16:32:48.509+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-10T16:32:49.819+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-06-11T04:45:28.451+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_pythonoperator.second_task scheduled__2023-06-07T00:00:00+00:00 [queued]>
[2023-06-11T04:45:28.618+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_pythonoperator.second_task scheduled__2023-06-07T00:00:00+00:00 [queued]>
[2023-06-11T04:45:28.618+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 6
[2023-06-11T04:45:28.942+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): second_task> on 2023-06-07 00:00:00+00:00
[2023-06-11T04:45:29.009+0000] {standard_task_runner.py:57} INFO - Started process 277 to run task
[2023-06-11T04:45:29.037+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag_pythonoperator', 'second_task', 'scheduled__2023-06-07T00:00:00+00:00', '--job-id', '72', '--raw', '--subdir', 'DAGS_FOLDER/python_operator_dag.py', '--cfg-path', '/tmp/tmpsw0oyz7t']
[2023-06-11T04:45:29.075+0000] {standard_task_runner.py:85} INFO - Job 72: Subtask second_task
[2023-06-11T04:45:29.818+0000] {task_command.py:410} INFO - Running <TaskInstance: dag_pythonoperator.second_task scheduled__2023-06-07T00:00:00+00:00 [running]> on host 4b1b5d40d165
[2023-06-11T04:45:32.109+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Raja' AIRFLOW_CTX_DAG_ID='dag_pythonoperator' AIRFLOW_CTX_TASK_ID='second_task' AIRFLOW_CTX_EXECUTION_DATE='2023-06-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-06-07T00:00:00+00:00'
[2023-06-11T04:45:32.116+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/python_operator_dag.py", line 16, in retur_values
    first_name=ti.xcom_pull(task_ids=get_name,key='first_name')
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2441, in xcom_pull
    task_id_whens = {tid: i for i, tid in enumerate(task_ids)}
TypeError: 'function' object is not iterable
[2023-06-11T04:45:32.256+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_pythonoperator, task_id=second_task, execution_date=20230607T000000, start_date=20230611T044528, end_date=20230611T044532
[2023-06-11T04:45:32.343+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 72 for task second_task ('function' object is not iterable; 277)
[2023-06-11T04:45:32.405+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-11T04:45:32.955+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
