[2023-06-11T04:48:32.398+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: first_dag_02.first_task scheduled__2021-09-19T00:00:00+00:00 [queued]>
[2023-06-11T04:48:32.542+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: first_dag_02.first_task scheduled__2021-09-19T00:00:00+00:00 [queued]>
[2023-06-11T04:48:32.543+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 6
[2023-06-11T04:48:35.882+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): first_task> on 2021-09-19 00:00:00+00:00
[2023-06-11T04:48:36.095+0000] {standard_task_runner.py:57} INFO - Started process 643 to run task
[2023-06-11T04:48:36.236+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'first_dag_02', 'first_task', 'scheduled__2021-09-19T00:00:00+00:00', '--job-id', '183', '--raw', '--subdir', 'DAGS_FOLDER/First_dag.py', '--cfg-path', '/tmp/tmpmci1qzgy']
[2023-06-11T04:48:36.236+0000] {standard_task_runner.py:85} INFO - Job 183: Subtask first_task
[2023-06-11T04:48:39.836+0000] {task_command.py:410} INFO - Running <TaskInstance: first_dag_02.first_task scheduled__2021-09-19T00:00:00+00:00 [running]> on host 4b1b5d40d165
[2023-06-11T04:48:44.958+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Raja' AIRFLOW_CTX_DAG_ID='first_dag_02' AIRFLOW_CTX_TASK_ID='first_task' AIRFLOW_CTX_EXECUTION_DATE='2021-09-19T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2021-09-19T00:00:00+00:00'
[2023-06-11T04:48:44.965+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-06-11T04:48:44.967+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'echo hello world, this is the first task!']
[2023-06-11T04:48:45.102+0000] {subprocess.py:86} INFO - Output:
[2023-06-11T04:48:45.328+0000] {subprocess.py:93} INFO - hello world, this is the first task!
[2023-06-11T04:48:45.527+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-06-11T04:48:45.886+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=first_dag_02, task_id=first_task, execution_date=20210919T000000, start_date=20230611T044832, end_date=20230611T044845
[2023-06-11T04:48:46.399+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-06-11T04:48:47.499+0000] {taskinstance.py:2651} INFO - 2 downstream tasks scheduled from follow-on schedule check
[2023-06-11T08:25:25.580+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: first_dag_02.first_task scheduled__2021-09-19T00:00:00+00:00 [queued]>
[2023-06-11T08:25:26.300+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: first_dag_02.first_task scheduled__2021-09-19T00:00:00+00:00 [queued]>
[2023-06-11T08:25:26.301+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 6
[2023-06-11T08:25:27.056+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): first_task> on 2021-09-19 00:00:00+00:00
[2023-06-11T08:25:27.072+0000] {standard_task_runner.py:57} INFO - Started process 1072 to run task
[2023-06-11T08:25:27.384+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'first_dag_02', 'first_task', 'scheduled__2021-09-19T00:00:00+00:00', '--job-id', '334', '--raw', '--subdir', 'DAGS_FOLDER/First_dag.py', '--cfg-path', '/tmp/tmpl_2rcabd']
[2023-06-11T08:25:27.385+0000] {standard_task_runner.py:85} INFO - Job 334: Subtask first_task
[2023-06-11T08:25:28.662+0000] {task_command.py:410} INFO - Running <TaskInstance: first_dag_02.first_task scheduled__2021-09-19T00:00:00+00:00 [running]> on host 492037cdd057
[2023-06-11T08:25:39.135+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Raja' AIRFLOW_CTX_DAG_ID='first_dag_02' AIRFLOW_CTX_TASK_ID='first_task' AIRFLOW_CTX_EXECUTION_DATE='2021-09-19T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2021-09-19T00:00:00+00:00'
[2023-06-11T08:25:39.393+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-06-11T08:25:39.573+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'echo hello world, this is the first task!']
[2023-06-11T08:25:39.760+0000] {subprocess.py:86} INFO - Output:
[2023-06-11T08:25:39.837+0000] {subprocess.py:93} INFO - hello world, this is the first task!
[2023-06-11T08:25:39.841+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-06-11T08:25:40.627+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=first_dag_02, task_id=first_task, execution_date=20210919T000000, start_date=20230611T082525, end_date=20230611T082540
[2023-06-11T08:25:41.499+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-06-11T08:25:42.657+0000] {taskinstance.py:2651} INFO - 2 downstream tasks scheduled from follow-on schedule check
[2023-06-11T08:50:23.047+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: first_dag_02.first_task scheduled__2021-09-19T00:00:00+00:00 [queued]>
[2023-06-11T08:50:23.306+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: first_dag_02.first_task scheduled__2021-09-19T00:00:00+00:00 [queued]>
[2023-06-11T08:50:23.317+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 6
[2023-06-11T08:50:23.697+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): first_task> on 2021-09-19 00:00:00+00:00
[2023-06-11T08:50:23.713+0000] {standard_task_runner.py:57} INFO - Started process 873 to run task
[2023-06-11T08:50:23.728+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'first_dag_02', 'first_task', 'scheduled__2021-09-19T00:00:00+00:00', '--job-id', '266', '--raw', '--subdir', 'DAGS_FOLDER/First_dag.py', '--cfg-path', '/tmp/tmpxg0164mx']
[2023-06-11T08:50:23.730+0000] {standard_task_runner.py:85} INFO - Job 266: Subtask first_task
[2023-06-11T08:50:24.343+0000] {task_command.py:410} INFO - Running <TaskInstance: first_dag_02.first_task scheduled__2021-09-19T00:00:00+00:00 [running]> on host 964e508aad03
[2023-06-11T08:50:26.337+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Raja' AIRFLOW_CTX_DAG_ID='first_dag_02' AIRFLOW_CTX_TASK_ID='first_task' AIRFLOW_CTX_EXECUTION_DATE='2021-09-19T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2021-09-19T00:00:00+00:00'
[2023-06-11T08:50:26.341+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-06-11T08:50:26.343+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'echo hello world, this is the first task!']
[2023-06-11T08:50:26.468+0000] {subprocess.py:86} INFO - Output:
[2023-06-11T08:50:26.504+0000] {subprocess.py:93} INFO - hello world, this is the first task!
[2023-06-11T08:50:26.510+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-06-11T08:50:26.708+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=first_dag_02, task_id=first_task, execution_date=20210919T000000, start_date=20230611T085023, end_date=20230611T085026
[2023-06-11T08:50:26.895+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-06-11T08:50:27.314+0000] {taskinstance.py:2651} INFO - 2 downstream tasks scheduled from follow-on schedule check
[2023-06-11T10:48:20.949+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: first_dag_02.first_task scheduled__2021-09-19T00:00:00+00:00 [queued]>
[2023-06-11T10:48:21.590+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: first_dag_02.first_task scheduled__2021-09-19T00:00:00+00:00 [queued]>
[2023-06-11T10:48:21.591+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 6
[2023-06-11T10:48:23.884+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): first_task> on 2021-09-19 00:00:00+00:00
[2023-06-11T10:48:24.787+0000] {standard_task_runner.py:57} INFO - Started process 931 to run task
[2023-06-11T10:48:25.008+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'first_dag_02', 'first_task', 'scheduled__2021-09-19T00:00:00+00:00', '--job-id', '257', '--raw', '--subdir', 'DAGS_FOLDER/First_dag.py', '--cfg-path', '/tmp/tmp_s7fodtb']
[2023-06-11T10:48:25.303+0000] {standard_task_runner.py:85} INFO - Job 257: Subtask first_task
[2023-06-11T10:49:40.300+0000] {job.py:216} ERROR - Job heartbeat got an exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3366, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/jobs/job.py", line 187, in heartbeat
    session.merge(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 3062, in merge
    _resolve_conflict_map=_resolve_conflict_map,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 3140, in _merge
    options=options,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2861, in get
    execution_options=execution_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2979, in _get_impl
    load_options=load_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/loading.py", line 534, in load_on_pk_identity
    bind_arguments=bind_arguments,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1556, in _connection_for_bind
    engine, execution_options
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3320, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3399, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3370, in _wrap_pool_connect
    e, dialect, self
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2204, in _handle_dbapi_exception_noconnection
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3366, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2023-06-11T10:52:26.865+0000] {task_command.py:410} INFO - Running <TaskInstance: first_dag_02.first_task scheduled__2021-09-19T00:00:00+00:00 [running]> on host 7586ce0070ac
[2023-06-11T10:52:40.207+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Raja' AIRFLOW_CTX_DAG_ID='first_dag_02' AIRFLOW_CTX_TASK_ID='first_task' AIRFLOW_CTX_EXECUTION_DATE='2021-09-19T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2021-09-19T00:00:00+00:00'
[2023-06-11T10:52:40.865+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-06-11T10:52:40.930+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'echo hello world, this is the first task!']
[2023-06-11T10:52:42.143+0000] {subprocess.py:86} INFO - Output:
[2023-06-11T10:52:42.265+0000] {subprocess.py:93} INFO - hello world, this is the first task!
[2023-06-11T10:52:42.269+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-06-11T10:52:44.810+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=first_dag_02, task_id=first_task, execution_date=20210919T000000, start_date=20230611T104821, end_date=20230611T105244
[2023-06-11T10:52:47.439+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-06-11T10:52:50.826+0000] {taskinstance.py:2651} INFO - 2 downstream tasks scheduled from follow-on schedule check
