[2023-06-11T04:54:28.173+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: first_dag_02.thrid_task scheduled__2021-10-22T00:00:00+00:00 [queued]>
[2023-06-11T04:54:28.715+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: first_dag_02.thrid_task scheduled__2021-10-22T00:00:00+00:00 [queued]>
[2023-06-11T04:54:28.716+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 6
[2023-06-11T04:54:29.285+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): thrid_task> on 2021-10-22 00:00:00+00:00
[2023-06-11T04:54:29.310+0000] {standard_task_runner.py:57} INFO - Started process 1153 to run task
[2023-06-11T04:54:29.338+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'first_dag_02', 'thrid_task', 'scheduled__2021-10-22T00:00:00+00:00', '--job-id', '340', '--raw', '--subdir', 'DAGS_FOLDER/First_dag.py', '--cfg-path', '/tmp/tmpv9i140_9']
[2023-06-11T04:54:29.341+0000] {standard_task_runner.py:85} INFO - Job 340: Subtask thrid_task
[2023-06-11T04:54:30.090+0000] {task_command.py:410} INFO - Running <TaskInstance: first_dag_02.thrid_task scheduled__2021-10-22T00:00:00+00:00 [running]> on host 4b1b5d40d165
[2023-06-11T04:54:36.803+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Raja' AIRFLOW_CTX_DAG_ID='first_dag_02' AIRFLOW_CTX_TASK_ID='thrid_task' AIRFLOW_CTX_EXECUTION_DATE='2021-10-22T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2021-10-22T00:00:00+00:00'
[2023-06-11T04:54:36.819+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-06-11T04:54:36.833+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'echo hey, I am task3 and will be running after task1 at the same time as task2!']
[2023-06-11T04:54:37.443+0000] {subprocess.py:86} INFO - Output:
[2023-06-11T04:54:37.630+0000] {subprocess.py:93} INFO - hey, I am task3 and will be running after task1 at the same time as task2!
[2023-06-11T04:54:37.633+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-06-11T04:54:40.448+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=first_dag_02, task_id=thrid_task, execution_date=20211022T000000, start_date=20230611T045428, end_date=20230611T045440
[2023-06-11T04:54:44.847+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-06-11T04:54:46.200+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-06-11T08:32:00.973+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: first_dag_02.thrid_task scheduled__2021-10-22T00:00:00+00:00 [queued]>
[2023-06-11T08:32:02.353+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: first_dag_02.thrid_task scheduled__2021-10-22T00:00:00+00:00 [queued]>
[2023-06-11T08:32:02.353+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 6
[2023-06-11T08:32:02.530+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): thrid_task> on 2021-10-22 00:00:00+00:00
[2023-06-11T08:32:02.545+0000] {standard_task_runner.py:57} INFO - Started process 1510 to run task
[2023-06-11T08:32:03.047+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'first_dag_02', 'thrid_task', 'scheduled__2021-10-22T00:00:00+00:00', '--job-id', '460', '--raw', '--subdir', 'DAGS_FOLDER/First_dag.py', '--cfg-path', '/tmp/tmpindrvhwz']
[2023-06-11T08:32:03.052+0000] {standard_task_runner.py:85} INFO - Job 460: Subtask thrid_task
[2023-06-11T08:32:03.094+0000] {cli_action_loggers.py:135} WARNING - Failed to log action (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2023-06-11T08:32:03.325+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 460 for task thrid_task ((psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8); 1510)
[2023-06-11T08:32:03.831+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-11T08:32:03.893+0000] {taskinstance.py:2660} INFO - Skipping mini scheduling run due to exception: None
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3366, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2611, in schedule_downstream_tasks
    session=session,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 2870, in one
    return self._iter().one()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 2919, in _iter
    execution_options={"_sa_orm_load_options": self.load_options},
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1556, in _connection_for_bind
    engine, execution_options
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3320, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3399, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3370, in _wrap_pool_connect
    e, dialect, self
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2204, in _handle_dbapi_exception_noconnection
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3366, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2023-06-11T08:52:50.039+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: first_dag_02.thrid_task scheduled__2021-10-22T00:00:00+00:00 [queued]>
[2023-06-11T08:52:50.325+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: first_dag_02.thrid_task scheduled__2021-10-22T00:00:00+00:00 [queued]>
[2023-06-11T08:52:50.325+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 6
[2023-06-11T08:52:50.790+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): thrid_task> on 2021-10-22 00:00:00+00:00
[2023-06-11T08:52:50.847+0000] {standard_task_runner.py:57} INFO - Started process 1426 to run task
[2023-06-11T08:52:50.910+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'first_dag_02', 'thrid_task', 'scheduled__2021-10-22T00:00:00+00:00', '--job-id', '442', '--raw', '--subdir', 'DAGS_FOLDER/First_dag.py', '--cfg-path', '/tmp/tmpm46znbkc']
[2023-06-11T08:52:50.932+0000] {standard_task_runner.py:85} INFO - Job 442: Subtask thrid_task
[2023-06-11T08:52:51.689+0000] {task_command.py:410} INFO - Running <TaskInstance: first_dag_02.thrid_task scheduled__2021-10-22T00:00:00+00:00 [running]> on host 964e508aad03
[2023-06-11T08:52:53.849+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Raja' AIRFLOW_CTX_DAG_ID='first_dag_02' AIRFLOW_CTX_TASK_ID='thrid_task' AIRFLOW_CTX_EXECUTION_DATE='2021-10-22T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2021-10-22T00:00:00+00:00'
[2023-06-11T08:52:53.853+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-06-11T08:52:53.854+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'echo hey, I am task3 and will be running after task1 at the same time as task2!']
[2023-06-11T08:52:54.044+0000] {subprocess.py:86} INFO - Output:
[2023-06-11T08:52:54.089+0000] {subprocess.py:93} INFO - hey, I am task3 and will be running after task1 at the same time as task2!
[2023-06-11T08:52:54.096+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-06-11T08:52:54.436+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=first_dag_02, task_id=thrid_task, execution_date=20211022T000000, start_date=20230611T085250, end_date=20230611T085254
[2023-06-11T08:52:54.755+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-06-11T08:52:55.066+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-06-11T11:03:07.298+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: first_dag_02.thrid_task scheduled__2021-10-22T00:00:00+00:00 [queued]>
[2023-06-11T11:03:07.754+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: first_dag_02.thrid_task scheduled__2021-10-22T00:00:00+00:00 [queued]>
[2023-06-11T11:03:07.754+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 6
[2023-06-11T11:03:13.159+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): thrid_task> on 2021-10-22 00:00:00+00:00
[2023-06-11T11:03:13.182+0000] {standard_task_runner.py:57} INFO - Started process 1594 to run task
[2023-06-11T11:03:13.265+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'first_dag_02', 'thrid_task', 'scheduled__2021-10-22T00:00:00+00:00', '--job-id', '440', '--raw', '--subdir', 'DAGS_FOLDER/First_dag.py', '--cfg-path', '/tmp/tmpbvl2vblf']
[2023-06-11T11:03:13.276+0000] {standard_task_runner.py:85} INFO - Job 440: Subtask thrid_task
[2023-06-11T11:03:15.246+0000] {task_command.py:410} INFO - Running <TaskInstance: first_dag_02.thrid_task scheduled__2021-10-22T00:00:00+00:00 [running]> on host 7586ce0070ac
