[2023-06-12T08:43:11.676+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Var_dag_02.dag_var scheduled__2023-06-11T00:00:00+00:00 [queued]>
[2023-06-12T08:43:11.721+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Var_dag_02.dag_var scheduled__2023-06-11T00:00:00+00:00 [queued]>
[2023-06-12T08:43:11.722+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 6
[2023-06-12T08:43:11.772+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): dag_var> on 2023-06-11 00:00:00+00:00
[2023-06-12T08:43:11.781+0000] {standard_task_runner.py:57} INFO - Started process 1632 to run task
[2023-06-12T08:43:11.797+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Var_dag_02', 'dag_var', 'scheduled__2023-06-11T00:00:00+00:00', '--job-id', '299', '--raw', '--subdir', 'DAGS_FOLDER/variable_dag.py', '--cfg-path', '/tmp/tmppcmu0jm9']
[2023-06-12T08:43:11.797+0000] {standard_task_runner.py:85} INFO - Job 299: Subtask dag_var
[2023-06-12T08:43:12.043+0000] {task_command.py:410} INFO - Running <TaskInstance: Var_dag_02.dag_var scheduled__2023-06-11T00:00:00+00:00 [running]> on host 03cd9a7904e9
[2023-06-12T08:43:12.556+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Raja' AIRFLOW_CTX_DAG_ID='Var_dag_02' AIRFLOW_CTX_TASK_ID='dag_var' AIRFLOW_CTX_EXECUTION_DATE='2023-06-11T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-06-11T00:00:00+00:00'
[2023-06-12T08:43:12.595+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/variable_dag.py", line 7, in print_variable
    var_sample_json=Variable.get("sample_json'",deserialize_json=True)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 142, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: "Variable sample_json' does not exist"
[2023-06-12T08:43:12.619+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=Var_dag_02, task_id=dag_var, execution_date=20230611T000000, start_date=20230612T084311, end_date=20230612T084312
[2023-06-12T08:43:12.643+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 299 for task dag_var ("Variable sample_json' does not exist"; 1632)
[2023-06-12T08:43:12.667+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-12T08:43:12.726+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
