[2023-06-12T08:59:22.842+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Var_dag_06.dag_var manual__2023-06-12T08:59:17.597936+00:00 [queued]>
[2023-06-12T08:59:22.874+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Var_dag_06.dag_var manual__2023-06-12T08:59:17.597936+00:00 [queued]>
[2023-06-12T08:59:22.875+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 6
[2023-06-12T08:59:22.924+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): dag_var> on 2023-06-12 08:59:17.597936+00:00
[2023-06-12T08:59:22.933+0000] {standard_task_runner.py:57} INFO - Started process 1887 to run task
[2023-06-12T08:59:22.948+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Var_dag_06', 'dag_var', 'manual__2023-06-12T08:59:17.597936+00:00', '--job-id', '310', '--raw', '--subdir', 'DAGS_FOLDER/variable_dag.py', '--cfg-path', '/tmp/tmp8ljhz_hw']
[2023-06-12T08:59:22.949+0000] {standard_task_runner.py:85} INFO - Job 310: Subtask dag_var
[2023-06-12T08:59:23.116+0000] {task_command.py:410} INFO - Running <TaskInstance: Var_dag_06.dag_var manual__2023-06-12T08:59:17.597936+00:00 [running]> on host 03cd9a7904e9
[2023-06-12T08:59:23.430+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Raja' AIRFLOW_CTX_DAG_ID='Var_dag_06' AIRFLOW_CTX_TASK_ID='dag_var' AIRFLOW_CTX_EXECUTION_DATE='2023-06-12T08:59:17.597936+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-06-12T08:59:17.597936+00:00'
[2023-06-12T08:59:23.506+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/variable_dag.py", line 8, in print_variable
    var_env_test=Variable.get("test")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 142, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable test does not exist'
[2023-06-12T08:59:23.528+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=Var_dag_06, task_id=dag_var, execution_date=20230612T085917, start_date=20230612T085922, end_date=20230612T085923
[2023-06-12T08:59:23.558+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 310 for task dag_var ('Variable test does not exist'; 1887)
[2023-06-12T08:59:23.596+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-12T08:59:23.658+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
